/**
 * Randomize 按钮使用的随机提示词库。
 *
 * 针对 Agnes Image 2.5 Flash（文生图）优化：
 * - 结构统一为「主体 + 场景 + 风格 + 光影 + 画质」，模型对这种写法响应最稳定
 * - 刻意强调纹理密集、色彩层次丰富、细节繁复的画面，
 *   本地融合时每个二维码模块都能取到有内容的背景纹理，视觉上更融入画面
 * - 避免使用极简、纯色背景、大面积留白这类描述，会让融合后的模块显得单调
 *
 * 三个语言的条目按 index 一一对应（同一主题）。
 */

const promptsZh: string[] = [
  "深海珊瑚礁，成群的热带鱼穿梭在珊瑚与海葵之间，阳光透过水面形成道道光柱，色彩浓郁饱和，细节繁复，电影级光影，超高清",
  "璀璨银河与旋涡星云，无数星辰铺满深蓝夜空，星团与星尘交织，冷色调辉光，层次丰富，天文摄影质感，极致细节",
  "抽象几何构成，不规则多边形与流动色块交错叠加，包豪斯配色，硬边与渐变并存，高饱和撞色，现代设计感，细节精致",
  "非洲大草原日落，象群与长颈鹿剪影漫步在金色草浪中，远处猴面包树，暖橙色逆光，大气磅礴，野生动物摄影，超高细节",
  "赛博朋克未来都市夜景，霓虹招牌与全息广告牌密布，雨天湿滑街道倒映着斑斓灯光，蓝紫与品红色调，电影感，细节繁复",
  "古罗马神庙遗迹，巨型大理石立柱与拱券整齐排列，藤蔓攀爬在斑驳石墙上，午后斜阳，暖米黄色调，建筑摄影，纹理细腻",
  "北美原住民图腾柱，红黑白三色雕刻着鹰、狼与雷鸟的面部纹样，强烈的几何线条，粗犷刀痕，民族艺术风格，细节丰富",
  "古代石刻浮雕，细腻凿痕勾勒出人物与卷草纹，青灰砂岩质地，侧光勾勒出强烈立体感，博物馆级质感，纹理清晰",
  "深秋枫林，火红与金黄的落叶铺满小径，逆光下叶脉通透，暖色调浓郁，微距层次丰富，自然摄影，超高细节",
  "雪山雾凇清晨，松枝挂满洁白雪晶与冰挂，晨雾在林间流动，冷蓝与纯白交织，静谧通透，风光摄影，细节极致",
  "悬浮的 3D 几何体，多面体、圆环与棱柱在空间中交错，柔和环境光遮蔽，磨砂与金属材质混搭，极简白色影棚，渲染级质感",
  "古埃及神庙墙壁，密布的象形文字与圣甲虫、荷鲁斯之眼浮雕，砂岩的沙金色，火把暖光斜照，考古纪实感，纹理斑驳",
  "托斯卡纳田园风光，起伏的丘陵上麦田与丝柏树成行排列，农舍点缀其间，黄昏蜜金色光线，油画般厚重，细节丰富",
  "梵高《星月夜》风格，旋涡状的星空与流动的云，夸张的笔触与厚涂肌理，深蓝与明黄强烈对比，后印象派，画面充满动感",
  "高级定制时装大片，丝绸与薄纱层叠的礼服，精致刺绣与珠饰，工作室柔光与硬光结合，时尚杂志质感，面料纹理纤毫毕现",
  "精灵魔法森林，发光的蘑菇与漂浮的金色光点弥漫在空气中，古老藤蔓缠绕巨树，梦幻紫蓝色调，奇幻插画风格，细节精致",
  "童话小镇，鹅卵石铺就的窄巷两侧是斜顶木筋房，窗台垂下鲜艳的天竺葵，午后暖阳，故事书插画风格，色彩明快，细节丰富",
  "日式动画风格场景，夏日乡间小路与电线杆，积雨云堆积的湛蓝天空，赛璐璐上色与柔和渐变，吉卜力式细腻背景，画面通透",
  "复古旅行海报，上世纪中叶的平涂色块与粗描边，褪色的橙黄与青绿，做旧纸张颗粒质感，丝网印刷风格，构图简洁有力",
  "中国水墨山水，远山如黛，留白处云雾流动，近景松枝与孤舟，浓淡干湿的墨色层次，宣纸肌理，文人画意境，笔触细腻",
  "万花筒图案，对称的彩色玻璃碎片与花瓣无限重复，彩虹光谱全色域，中心放射状构图，炫目华丽，细节精密",
  "扑克牌与赌场元素，红桃黑桃梅花方片的镀金浮雕，散落的筹码与丝绒桌面，聚光灯下的丝绒质感，奢华暗调，细节繁复",
  "美漫超级英雄场景，粗黑轮廓线与网点印刷质感，夸张的动态透视，高饱和的红蓝黄撞色，城市天台背景，漫画分镜构图",
  "古典油画肖像，伦勃朗式布光，深色背景衬托出人物面部与蕾丝领口的细腻质感，厚涂油彩肌理，写实主义，笔触可见",
  "爵士酒吧夜景，黄铜萨克斯与老式麦克风，舞台上弥漫着暖黄烟雾，深色木质与皮革质感，慵暧的氛围光，胶片颗粒感",
  "希腊神话场景，大理石神殿前的诸神雕像，橄榄树与爱琴海的湛蓝背景，金色的神圣光辉，古典主义壁画风格，细节丰富",
  "多肉植物微距，层层叠叠的莲座状叶片覆着白粉，叶尖泛着粉红与青蓝，浅景深，柔和自然光，植物摄影，质感细腻",
  "民间刺绣纹样，彩色丝线绣出的繁复花卉与几何边饰，亚麻底布的粗织肌理，针脚清晰可见，民俗艺术配色，细节精致",
  "钻石与宝石特写，多面切割折射出璀璨火彩，深邃的蓝宝石与祖母绿环绕，黑色丝绒背景，聚光灯下的高光，珠宝级质感",
  "古典大理石雕塑，细腻的衣褶与肌肉线条，侧光勾勒出柔和阴影，博物馆展厅的暖白灯光，文艺复兴风格，纹理逼真",
  "芭蕾舞者瞬间定格，薄纱裙摆在空中舒展，舞台聚光灯打出戏剧性轮廓，深色背景，舞者的肌肉与织物细节清晰，动感十足",
  "森林精灵聚落，树洞中的微小木屋与灯笼，苔藓与蕨类铺满地表，晨雾中的丁达尔光，奇幻绘本风格，细节丰富，氛围温暖",
  "浪漫爱心主题，飘浮的红色心形气球与玫瑰花瓣，柔和的粉色与金色光晕，浅景深光斑，甜蜜梦幻氛围，画面柔和细腻",
  "精密机械内部，交错的黄铜齿轮、游丝与轴承，冷蓝金属光泽，微距浅景深，工业设计蓝图背景，工程美学，细节极致",
  "热气球群升空，数十只彩色气球飘在辽阔的高原上空，晨光染红云层，俯瞰视角，旅行摄影质感，色彩明快，细节丰富",
  "藏传佛教曼陀罗，繁复对称的坛城图案，金线与朱红青蓝矿物颜料，细密的卷草与莲花纹，唐卡艺术风格，精密华丽",
  "维多利亚时代客厅，深色胡桃木护墙板与丝绒窗帘，繁复的卷草雕花与黄铜烛台，煤气灯的暖黄光，哥特复兴风格，细节繁复",
  "电影片场一隅，老式摄影机与轨道，聚光灯打出锥形光柱，空气中悬浮的尘埃，电影胶片的颗粒与色调，幕后纪实感，氛围浓厚",
  "蒸汽朋克工坊，裸露的铜管、压力表与铆钉铁板，齿轮咬合转动，蒸汽从阀门缝隙喷出，琥珀色工业光，复古未来主义，质感厚重",
  "虚拟现实空间，发光的网格地平线向远方无限延伸，悬浮的几何体与数据流，霓虹青紫渐变，数字艺术风格，科幻质感，细节繁密",
  "海盗船航海场景，鼓满的风帆与复杂的索具，暴风巨浪与阴云密布的天空，木船甲板纹理清晰，史诗冒险氛围，油画质感",
  "科技电路梦境，密集的电路走线与发光节点在深色基板上交织，青色与品红的数据流脉冲，微观电子世界，赛博质感，细节精密",
  "圣诞主题场景，挂满彩灯与金箔装饰的圣诞树，松枝、姜饼与红丝绒，暖黄烛光与窗外飘雪，温馨浓郁的节日氛围，细节丰富",
  "非洲部落庆典，彩绘面具与珠饰头冠，羽毛与兽皮的层叠质感，篝火的橙红火光跳动，强烈的图案化装饰，民族志摄影，纹理清晰",
  "游乐园黄昏，摩天轮与过山车的钢架结构，闪烁的彩灯串与远处烟花，暖橙与紫蓝的暮色渐变，欢乐热闹氛围，细节繁复",
  "迷雾森林深处，参天古木与垂挂的地衣，光束穿透薄雾形成丁达尔效应，苔藓的翠绿与树皮的深褐，静谧神秘，自然摄影，层次丰富",
  "海边度假小屋，白色栅栏与贝壳沙滩，蓝白相间的木质露台，正午明亮的海滨光线，清澈通透的青绿色海水，旅行杂志质感",
  "樱花树下野餐，粉白花瓣飘落在格纹餐布与草地上，春日的柔和散射光，清新淡雅的粉绿色调，日系摄影风格，画面温柔细腻",
  "空荡的老剧场舞台，深红丝绒帷幕半掩，一束孤独的顶光打在木地板上，空气中浮动的尘埃，复古华丽的装饰纹样，静谧氛围感",
  "河谷露营地，清澈溪流环绕着帐篷与野餐桌，树冠间漏下的斑驳阳光，水面映着云影与树影，夏日户外氛围，自然摄影，细节丰富",
];

const promptsEn: string[] = [
  "vibrant coral reef teeming with tropical fish weaving between corals and anemones, sunbeams piercing through turquoise water, rich saturated colors, highly detailed, cinematic lighting, ultra hd",
  "spiral galaxy and swirling nebula, countless stars scattered across deep blue night sky, star clusters and cosmic dust, cool blue glow, rich depth, astrophotography, extreme detail",
  "abstract geometric composition, irregular polygons and flowing color blocks overlapping, Bauhaus palette, hard edges with soft gradients, bold saturated color clash, modern design, refined detail",
  "African savanna at sunset, elephant herd and giraffe silhouettes walking through golden grass, distant baobab trees, warm orange backlight, epic scale, wildlife photography, ultra detailed",
  "cyberpunk futuristic cityscape at night, dense neon signs and holographic billboards, rain slicked streets reflecting colorful lights, blue purple and magenta tones, cinematic, intricate detail",
  "ancient Roman temple ruins, giant marble columns and arches in perfect rows, vines climbing weathered stone walls, afternoon raking light, warm beige tones, architectural photography, fine texture",
  "Native American totem pole, red black and white carved eagle wolf and thunderbird faces, bold geometric lines, rough chisel marks, folk art style, richly detailed",
  "ancient stone relief carving, fine chisel marks forming figures and scrollwork, grey sandstone grain, strong side lighting, museum grade quality, crisp texture",
  "autumn maple forest, fiery red and golden leaves carpeting a narrow path, backlit translucent leaf veins, warm saturated tones, macro detail, nature photography, ultra detailed",
  "snowy mountain rime at dawn, pine branches heavy with white frost and icicles, morning mist drifting through the forest, cold blue and pure white, serene and airy, landscape photography, extreme detail",
  "floating 3D geometric solids, polyhedra rings and prisms interlocking in space, soft ambient occlusion, matte and metallic materials, minimal white studio, render grade quality",
  "ancient Egyptian temple wall, densely packed hieroglyphs with scarab and eye of Horus reliefs, sandy golden sandstone, warm torchlight raking across, archaeological documentary feel, weathered texture",
  "Tuscan countryside, rolling hills with wheat fields and rows of cypress trees, farmhouses scattered across, golden hour honey light, painterly depth, richly detailed",
  "Van Gogh Starry Night style, swirling starry sky and flowing clouds, exaggerated brushstrokes and impasto texture, deep blue against vivid yellow, post impressionist, dynamic composition",
  "haute couture fashion editorial, silk and tulle layered gown, delicate embroidery and beadwork, studio soft and hard light combined, fashion magazine quality, fabric texture in fine detail",
  "fairy magic forest, glowing mushrooms and floating golden motes filling the air, ancient vines wrapping giant trees, dreamy purple blue tones, fantasy illustration, exquisite detail",
  "fairy tale village, cobblestone lanes lined with half timbered houses, bright geraniums spilling from window boxes, warm afternoon sun, storybook illustration, bright palette, richly detailed",
  "Japanese anime style scenery, summer country road and utility poles, towering cumulus clouds in deep blue sky, cel shading with soft gradients, Ghibli style detailed background, luminous",
  "retro travel poster, mid century flat color blocks and bold outlines, faded orange yellow and teal, aged paper grain, screen print style, clean powerful composition",
  "Chinese ink wash landscape, distant misty mountains, clouds drifting through negative space, pine branches and a lone boat in foreground, layered ink tones, rice paper texture, literati painting mood, delicate brushwork",
  "kaleidoscope pattern, symmetrical stained glass shards and petals repeating infinitely, full rainbow spectrum, radial composition, dazzling and ornate, precise detail",
  "poker and casino elements, gold embossed hearts spades clubs diamonds, scattered chips on velvet table, velvet texture under spotlight, luxurious dark tones, intricate detail",
  "American comic superhero scene, heavy black outlines and halftone print texture, exaggerated dynamic perspective, bold saturated red blue yellow clash, city rooftop backdrop, comic panel composition",
  "classical oil portrait, Rembrandt lighting, dark background setting off delicate face and lace collar, thick impasto oil texture, realism, visible brushstrokes",
  "jazz bar at night, brass saxophone and vintage microphone, warm amber haze drifting across the stage, dark wood and leather texture, languid ambient light, film grain",
  "Greek mythology scene, marble statues of the gods before a temple, olive trees and the azure Aegean beyond, golden divine radiance, classical mural style, richly detailed",
  "succulent plant macro, layered rosette leaves dusted with white bloom, pink and blue green leaf tips, shallow depth of field, soft natural light, botanical photography, delicate texture",
  "folk embroidery pattern, colorful silk threads forming elaborate florals and geometric borders, coarse linen weave ground, visible stitching, folk art palette, exquisite detail",
  "diamond and gemstone close up, multi facet cuts refracting brilliant fire, deep sapphire and emerald surrounding, black velvet background, spotlight highlights, jewelry grade quality",
  "classical marble sculpture, delicate drapery and muscle definition, side light carving soft shadows, warm white museum gallery lighting, renaissance style, lifelike texture",
  "ballet dancer frozen mid leap, tulle skirt billowing in the air, dramatic stage spotlight rim light, dark background, muscle and fabric detail crisp, full of motion",
  "forest sprite settlement, tiny wooden houses and lanterns inside tree hollows, moss and ferns carpeting the ground, morning god rays, fantasy picture book style, richly detailed, warm mood",
  "romantic heart theme, floating red heart balloons and rose petals, soft pink and golden glow, shallow depth of field bokeh, sweet dreamy mood, soft and delicate",
  "precision mechanism interior, interlocking brass gears hairspring and bearings, cold blue metallic sheen, macro shallow depth of field, industrial blueprint backdrop, engineering aesthetics, extreme detail",
  "hot air balloons ascending, dozens of colorful balloons drifting above a vast plateau, sunrise painting the clouds red, aerial view, travel photography, bright palette, richly detailed",
  "Tibetan Buddhist mandala, elaborate symmetrical cosmogram, gold linework with vermilion and mineral blue, dense scrollwork and lotus motifs, thangka art style, precise and ornate",
  "Victorian era parlor, dark walnut wainscoting and velvet curtains, elaborate scroll carvings and brass candelabra, warm yellow gaslight, gothic revival, intricate detail",
  "film set corner, vintage camera and dolly track, spotlights casting cone shaped beams, dust suspended in the air, film grain and color grading, behind the scenes documentary feel, dense atmosphere",
  "steampunk workshop, exposed copper pipes pressure gauges and riveted iron plates, gears meshing and turning, steam hissing from valve gaps, amber industrial light, retro futurism, heavy texture",
  "virtual reality space, glowing grid horizon stretching infinitely, floating geometry and data streams, neon cyan purple gradient, digital art style, sci fi texture, dense detail",
  "pirate ship at sea, billowing sails and complex rigging, storm waves and overcast sky, weathered wooden deck grain, epic adventure mood, oil painting quality",
  "technology circuit dreamscape, dense traces and glowing nodes interwoven on a dark substrate, cyan and magenta data pulses, microscopic electronic world, cyber texture, precise detail",
  "Christmas themed scene, tree hung with colored lights and gold ornaments, pine branches gingerbread and red velvet, warm candlelight and snow outside the window, cozy festive mood, richly detailed",
  "African tribal celebration, painted masks and beaded headdresses, layered feathers and hide texture, orange red bonfire flicker, bold patterned decoration, ethnographic photography, crisp texture",
  "amusement park at dusk, steel framework of ferris wheel and roller coaster, twinkling light strings and distant fireworks, warm orange to purple blue twilight gradient, joyful lively mood, intricate detail",
  "deep in a misty forest, towering ancient trees and hanging lichen, light shafts cutting through thin fog creating tyndall effect, mossy green against dark brown bark, serene mystery, nature photography, rich layers",
  "seaside holiday cottage, white picket fence and shell strewn sand, blue and white wooden deck, bright midday coastal light, clear turquoise water, travel magazine quality",
  "picnic under cherry blossoms, pink white petals falling on gingham cloth and grass, soft spring diffused light, fresh pale pink and green palette, Japanese photography style, gentle and delicate",
  "empty old theater stage, deep red velvet curtains half drawn, a single lonely overhead beam on wooden floorboards, dust floating in the air, ornate vintage decoration, tranquil atmosphere",
  "river valley campsite, clear stream curving around tents and picnic table, dappled sunlight through the canopy, water reflecting clouds and trees, summer outdoor mood, nature photography, richly detailed",
];

const promptsJp: string[] = [
  "色鮮やかなサンゴ礁、熱帯魚の群れがサンゴとイソギンチャクの間を泳ぐ、水面から差し込む光の柱、彩度の高い色彩、緻密なディテール、シネマティックな光、超高精細",
  "渦を巻く銀河と星雲、無数の星が深い青の夜空に散りばめられた、星団と宇宙のチリ、冷たい青の輝き、豊かな奥行き、天体写真、極めて詳細",
  "抽象的な幾何学構成、不規則な多角形と流れる色面が重なり合う、バウハウスの配色、硬いエッジと柔らかなグラデーション、鮮烈な色の衝突、モダンデザイン、精緻なディテール",
  "夕暮れのアフリカサバンナ、象の群れとキリンのシルエットが金色の草原を歩く、遠くのバオバブの木、暖かいオレンジの逆光、壮大なスケール、野生動物写真、超高精細",
  "サイバーパンクな未来都市の夜景、密集したネオンサインとホログラム広告、雨に濡れた路面が色とりどりの光を反射、青紫とマゼンタの色調、映画的、精緻なディテール",
  "古代ローマ神殿の遺跡、巨大な大理石の列柱とアーチが整然と並ぶ、風化した石壁に絡まる蔦、午後の斜光、温かみのあるベージュ、建築写真、細やかな質感",
  "ネイティブアメリカンのトーテムポール、赤黒白で彫られた鷲と狼と雷鳥の顔、力強い幾何学の線、荒々しい鑿跡、民族芸術のスタイル、細部まで豊か",
  "古代の石彫レリーフ、人物と唐草文様を刻む繊細な鑿痕、灰色の砂岩の肌合い、立体感を際立たせる側光、博物館級の品質、鮮明なテクスチャ",
  "秋の楓林、燃えるような赤と黄金の落ち葉が小径を覆う、逆光に透ける葉脈、暖かく彩度の高い色調、マクロのディテール、自然写真、超高精細",
  "夜明けの雪山の霧氷、松の枝にびっしりと白い霜と氷柱、朝霧が森を流れる、寒色の青と純白、静謐で澄んだ空気、風景写真、極めて詳細",
  "浮遊する3D幾何体、多面体とリングと角柱が空間で交差、柔らかなアンビエントオクルージョン、マットとメタリックの質感、ミニマルな白いスタジオ、レンダリング級の品質",
  "古代エジプト神殿の壁、びっしりと刻まれた象形文字とスカラベとホルスの目のレリーフ、砂金色の砂岩、たいまつの暖かな斜光、考古学的記録の趣、風化した質感",
  "トスカーナの田園風景、小麦畑と糸杉の列が連なる起伏のある丘陵、点在する農家、夕暮れの蜜色の光、絵画のような奥行き、細部まで豊か",
  "ゴッホ「星月夜」のスタイル、渦巻く星空と流れる雲、誇張された筆致と厚塗りのマチエール、深い青と鮮やかな黄色、ポスト印象派、動きのある構図",
  "オートクチュールのファッションエディトリアル、シルクとチュールを重ねたドレス、精緻な刺繍とビーズ、ソフトとハードを組み合わせたスタジオ光、ファッション誌の質感、生地の質感まで詳細",
  "妖精の魔法の森、光るキノコと漂う金色の光点が空気を満たす、古い蔦が巨木に絡まる、幻想的な紫青の色調、ファンタジーイラスト、精緻なディテール",
  "おとぎ話の村、石畳の細い路地に並ぶ木組みの家、窓辺からこぼれる鮮やかなゼラニウム、午後の暖かな日差し、絵本のイラスト、明快な色彩、細部まで豊か",
  "日本のアニメ風の風景、夏の田舎道と電柱、入道雲が湧き立つ真っ青な空、セル画の塗りと柔らかなグラデーション、ジブリ風の細密背景、透明感のある画面",
  "レトロなトラベルポスター、ミッドセンチュリーのフラットな色面と太い輪郭、褪せたオレンジイエローとティール、古紙の粒子感、シルクスクリーンの風合い、簡潔で力強い構図",
  "中国の水墨山水、遠く霞む山々、余白に流れる雲、手前の松の枝と孤舟、濃淡と乾湿の墨の階調、和紙の肌理、文人画の意境、繊細な筆致",
  "万華鏡のパターン、対称なステンドグラスの破片と花びらが無限に反復、虹の全色域、放射状の構図、眩く華麗、精密なディテール",
  "ポーカーとカジノの要素、金のエンボスが施されたハート・スペード・クラブ・ダイヤ、散らばるチップとベルベットのテーブル、スポットライトの下のベルベットの質感、豪華な暗調、精緻なディテール",
  "アメコミのスーパーヒーローの場面、太い黒の輪郭線と網点印刷の質感、誇張されたダイナミックなパース、鮮烈な赤青黄の衝突、街の屋上、コミックのコマ割り構図",
  "古典的な油彩肖像、レンブラント照明、暗い背景が顔とレースの襟の繊細な質感を引き立てる、厚塗りの油彩のマチエール、写実主義、筆致が見える",
  "夜のジャズバー、真鍮のサックスとヴィンテージマイク、舞台に漂う暖かな琥珀色の煙、濃い木と革の質感、けだるいアンビエント光、フィルムの粒子感",
  "ギリシャ神話の場面、神殿の前の大理石の神々の彫像、オリーブの木と紺碧のエーゲ海、黄金の神々しい光、古典主義の壁画スタイル、細部まで豊か",
  "多肉植物のマクロ、白粉をまとい幾重にも重なるロゼットの葉、ピンクと青緑に染まる葉先、浅い被写界深度、柔らかな自然光、植物写真、繊細な質感",
  "民族刺繍の文様、色糸で描かれた精緻な花と幾何学の縁飾り、粗織りの麻の下地、はっきり見えるステッチ、民俗芸術の配色、精緻なディテール",
  "ダイヤモンドと宝石の接写、多面カットが燦然と輝くファイア、深いサファイアとエメラルドが囲む、黒いベルベットの背景、スポットライトのハイライト、宝飾品級の質感",
  "古典的な大理石彫刻、繊細な衣の襞と筋肉のライン、柔らかな影を刻む側光、博物館の暖かい白い照明、ルネサンス様式、真に迫る質感",
  "跳躍の瞬間に凍りついたバレエダンサー、空中に広がるチュールのスカート、舞台のスポットライトが劇的な輪郭を描く、暗い背景、筋肉と布のディテールが鮮明、躍動感に満ちる",
  "森の妖精の集落、樹洞の中の小さな木の家とランタン、地表を覆う苔とシダ、朝霧のチンダル現象、ファンタジー絵本のスタイル、細部まで豊か、温かい雰囲気",
  "ロマンチックなハートのテーマ、浮かぶ赤いハートの風船とバラの花びら、柔らかなピンクと金色の光暈、浅い被写界深度のボケ、甘く夢見るような雰囲気、柔らかく繊細",
  "精密機械の内部、噛み合う真鍮の歯車とヒゲゼンマイと軸受、冷たい青の金属光沢、マクロの浅い被写界深度、工業図面の背景、エンジニアリングの美学、極めて詳細",
  "上昇する熱気球、色とりどりの数十の気球が広大な高原の上を漂う、雲を赤く染める日の出、俯瞰の視点、旅行写真、明快な色彩、細部まで豊か",
  "チベット仏教の曼荼羅、精緻で対称な曼荼羅の図、金の線描と朱と鉱物の青、びっしりと描かれた唐草と蓮の文様、タンカ芸術のスタイル、精密で華麗",
  "ヴィクトリア朝の客間、濃いクルミ材の腰板とベルベットのカーテン、精巧な唐草の彫刻と真鍮の燭台、ガス灯の暖かな黄色の光、ゴシックリバイバル、精緻なディテール",
  "映画撮影現場の一角、ヴィンテージカメラとドリーのレール、円錐状の光を投げるスポットライト、空気中に浮かぶ埃、フィルムの粒子感とカラーグレーディング、裏側の記録的な趣、濃密な雰囲気",
  "スチームパンクの工房、剥き出しの銅管と圧力計とリベットの鉄板、噛み合って回る歯車、バルブの隙間から噴き出す蒸気、琥珀色の工業光、レトロフューチャー、重厚な質感",
  "仮想現実の空間、無限に伸びる光るグリッドの地平線、浮遊する幾何体とデータストリーム、ネオンのシアンと紫のグラデーション、デジタルアートのスタイル、SF的な質感、密集したディテール",
  "海賊船の航海、膨らんだ帆と複雑な索具、嵐の大波と分厚い雲に覆われた空、風化した木の甲板の木目、壮大な冒険の雰囲気、油絵の質感",
  "テクノロジーの回路の夢、暗い基板上に絡み合う密集した配線と光るノード、シアンとマゼンタのデータの脈動、ミクロの電子の世界、サイバーな質感、精密なディテール",
  "クリスマスの場面、色とりどりの電飾と金のオーナメントをまとったツリー、松の枝とジンジャーブレッドと赤いベルベット、暖かな蝋燭の光と窓外の雪、心地よい祝祭の雰囲気、細部まで豊か",
  "アフリカの部族の祭り、彩色された仮面とビーズの頭飾り、層をなす羽根と獣皮の質感、焚き火のオレンジ赤い炎の揺らぎ、大胆な図案化された装飾、民族誌写真、鮮明なテクスチャ",
  "夕暮れの遊園地、観覧車とジェットコースターの鉄骨、瞬く電飾の列と遠くの花火、暖かなオレンジから紫青へのトワイライトの階調、賑やかで楽しい雰囲気、精緻なディテール",
  "霧深い森の奥、そびえる古木と垂れ下がる地衣類、薄霧を貫く光の筋がチンダル現象を生む、苔の緑と樹皮の焦げ茶、静謐な神秘、自然写真、豊かな階層",
  "海辺のコテージ、白い柵と貝殻の砂浜、青と白の木製デッキ、明るい真昼の海岸の光、澄んだターコイズブルーの海、トラベルマガジンの質感",
  "桜の木の下のピクニック、ギンガムチェックのクロスと草の上に舞い落ちる淡いピンク白の花びら、春の柔らかな拡散光、爽やかな淡いピンクと緑、日本の写真のスタイル、穏やかで繊細",
  "誰もいない古い劇場の舞台、半分開いた深紅のベルベットの幕、木の床に一筋の孤独なトップライト、空気に浮かぶ埃、華麗なヴィンテージ装飾、静謐な雰囲気",
  "河谷のキャンプ場、テントとピクニックテーブルの周りを蛇行する澄んだ小川、樹冠から漏れる斑模様の陽光、雲と木を映す水面、夏のアウトドアの雰囲気、自然写真、細部まで豊か",
];

/** 当前支持的语言 -> 对应提示词库 */
export const promptsByLocale: Record<"zh" | "en" | "jp", string[]> = {
  zh: promptsZh,
  en: promptsEn,
  jp: promptsJp,
};

/** 按语言取提示词库，未知语言回退到英文 */
export function getPrompts(locale?: string): string[] {
  if (locale && locale in promptsByLocale) {
    return promptsByLocale[locale as "zh" | "en" | "jp"];
  }
  return promptsEn;
}

/** @deprecated 保留向后兼容，等价于英文库 */
export const prompts: string[] = promptsEn;
